### ISSUE TITLE
Is it working on new Android APIs ?

### ISSUE THREAD

**Issue by louison** [dlgroupuoft/PScout#1]
Hi there, 

This is the first time I see this PScout code online. I looked into it a bit and at first sight it seems that it should be possible to run it on new Android APIs (> 22). 
Am I wrong ?

**Comment by davidlie** [comment]
None of the authors have personally tested this on newer Android versions, though I have received reports that others have run it on later Android versions successfully with no or only minor modifications.  Unfortunately, I don't have any data for very recent API versions, but definitely I did receive positive reports for APIs 23 and perhaps 24.

We're a small research group and we don't have the resources to PScout continously.  Please report back any findings you have if you decide to pursue.  Also please compare with the newer version of the tool https://github.com/zd2100/PScout and see which works better for you.

**Comment by b1ackm4x** [comment]
Hello, can some tell me the whick jdk should be used?  I try jdk1.6 1.7 1.8, all will stop with these errors
Exception in thread "main" java.lang.RuntimeException: Could not load classfile: java.lang.CharSequence
	at soot.coffi.Util.resolveFromClassFile(Util.java:75)
	at soot.CoffiClassSource.resolve(CoffiClassSource.java:39)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:194)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:140)
	at soot.SootResolver.resolveClass(SootResolver.java:124)
	at soot.Scene.tryLoadClass(Scene.java:406)
	at soot.Scene.loadBasicClasses(Scene.java:971)
	at dump.DumpClass.main(DumpClass.java:16)
